[PATHS]
  home=/home/jmrodriguez/projects/Encode/appris/code/src/firestar
  DB=/home/jmrodriguez/projects/Encode/appris/code/db
  tmp=/home/jmrodriguez/projects/Encode/appris/code/cached/APPRIS__PIPELINE__WORKSPACE/cache
  AFM=/home/jmrodriguez/projects/Encode/appris/code/db/another_fire_mess_web
[MYSQL]
  dbHost=localhost
  dbName=FireDB
  user=firedb
  pass=
[DATABASES]
  release=16Jan2013
  nrdb=sprot_clean_trembl_clean_70
  hhbdb=hhblits_
  hhprof=nr20_12Aug11
[SERVER]
  srv=caton
  user=inb
[CLUSTER_PATHS]
  home=/home/jmrodriguez/projects/Encode/appris/code/src/firestar
  root=/home/jmrodriguez/projects/Encode/appris/code/cached/APPRIS__PIPELINE__WORKSPACE/firestar/Analysis
  dir=/home/jmrodriguez/projects/Encode/appris/code/cached/APPRIS__PIPELINE__WORKSPACE/firestar
  DB=/home/jmrodriguez/projects/Encode/appris/code/db
  caton_queue=mpi
  ahsoka_queue=mpi
[PROGRAMS]
  bstbin=/opt/blast/2.2.26/src/bin
  muscle=/opt/muscle/3.8.31/muscle
  jmol=/opt/jmol/12.2.25/jmol-12.2.25
  ssearch=/opt/fasta/bin/ssearch36
  modeller=/opt/modeller/9.10/bin/mod9.10
  
